const Y_AXIS_LEFT = "left";
const Y_AXIS_RIGHT = "right";
const ORIENTATION_HORIZONTAL = "horizontal";
const ORIENTATION_VERTICAL = "vertical";
const CHART_LINE = "line";
const CHART_BAR = "bar";
const CHART_SCATTER = "scatter";
const CHART_AXIS_MIXED = "mixed";
const CHART_BUBBLE = "bubble";
const CHART_PIE = "pie";
const CHART_DONUT = "donut";
const CHART_PERCENTAGE = "percentage";
const CHART_RADAR = "radar";
const CHART_POLAR_AREA = "polar-area";
const CHART_HEATMAP = "heatmap";
const CHART_TIMESHEET = "timesheet";

const SVG_NS = "http://www.w3.org/2000/svg";

const ChartType = /*#__PURE__*/ Object.freeze({
  LINE: CHART_LINE,
  BAR: CHART_BAR,
  SCATTER: CHART_SCATTER,
  AXIS_MIXED: CHART_AXIS_MIXED,
  BUBBLE: CHART_BUBBLE,
  PIE: CHART_PIE,
  DONUT: CHART_DONUT,
  PERCENTAGE: CHART_PERCENTAGE,
  RADAR: CHART_RADAR,
  POLAR_AREA: CHART_POLAR_AREA,
  HEATMAP: CHART_HEATMAP,
  TIMESHEET: CHART_TIMESHEET,
});

const ChartOrientation = /*#__PURE__*/ Object.freeze({
  HORIZONTAL: ORIENTATION_HORIZONTAL,
  VERTICAL: ORIENTATION_VERTICAL,
});

const YAxisPosition = /*#__PURE__*/ Object.freeze({
  LEFT: Y_AXIS_LEFT,
  RIGHT: Y_AXIS_RIGHT,
});

const CHART_ORIENTATIONS = /*#__PURE__*/ Object.freeze([
  ORIENTATION_HORIZONTAL,
  ORIENTATION_VERTICAL,
]);

const Y_AXIS_POSITIONS = /*#__PURE__*/ Object.freeze([
  Y_AXIS_LEFT,
  Y_AXIS_RIGHT,
]);

const DEFAULT_COLORS = /*#__PURE__*/ Object.freeze([
  "#007AFF",
  "#AF52DE",
  "#FF3B30",
  "#FF9500",
  "#248A3D",
  "#5856D6",
  "#008C95",
]);

const HEATMAP_COLORS = /*#__PURE__*/ Object.freeze([
  "#E5E5EA",
  "#B7E4C7",
  "#74C69D",
  "#40916C",
  "#1B6B47",
]);

const CARTESIAN_TYPES = /*#__PURE__*/ Object.freeze([
  CHART_LINE,
  CHART_BAR,
  CHART_SCATTER,
  CHART_AXIS_MIXED,
  CHART_BUBBLE,
]);

const AGGREGATION_TYPES = /*#__PURE__*/ Object.freeze([
  CHART_PIE,
  CHART_DONUT,
  CHART_PERCENTAGE,
]);

const TYPES = /*#__PURE__*/ Object.freeze([
  ...CARTESIAN_TYPES,
  ...AGGREGATION_TYPES,
  CHART_RADAR,
  CHART_POLAR_AREA,
  CHART_HEATMAP,
  CHART_TIMESHEET,
]);

const MAJOR_GRID_DIVISIONS = 4;
const MAX_INDIVIDUAL_LINE_POINTS = 40;
const MAX_X_INSPECTOR_POINTS = 64;
const HORIZONTAL_LABEL_EDGE_INSET = 0;
const HORIZONTAL_LABEL_GAP = 4;
const VALUE_LABEL_GAP = 5;
const SERIES_SWATCH_DIAMETER = 8;
const LEGEND_LABEL_GAP = 8;
const LEGEND_LABEL_OFFSET = SERIES_SWATCH_DIAMETER + LEGEND_LABEL_GAP;
const LEGEND_ROW_HEIGHT = 20;
const LEGEND_BASELINE_INSET = 3;
const LEGEND_CONTENT_GAP = 20;
const MULTILINE_LABEL_HEIGHT = 13;
const POLAR_LABEL_EDGE_INSET = 12;
const POLAR_LABEL_GAP = 14;
const POLAR_LABEL_MIN_WIDTH = 44;
const DEFAULT_PAD_ANGLE = 1.5;
const DEFAULT_BAR_RADIUS = 3;
const DEFAULT_SECTOR_CORNER_RADIUS = 4;
const DEFAULT_PERCENTAGE_RADIUS = 6;
const MIN_SECTOR_SWEEP = 0.001;
const HEATMAP_MIN_CELL_WIDTH = 16;
const HOUR = 60 * 60 * 1000;
const DAY = 24 * HOUR;

const TIME_TICK_STEPS = /*#__PURE__*/ Object.freeze([
  HOUR,
  3 * HOUR,
  6 * HOUR,
  12 * HOUR,
  DAY,
  2 * DAY,
  7 * DAY,
  14 * DAY,
  30 * DAY,
  90 * DAY,
  365 * DAY,
]);

const COMPACT_NUMBER_FORMATTER = /*#__PURE__*/ new Intl.NumberFormat(undefined, {
  notation: "compact",
  maximumFractionDigits: 1,
});

const SMALL_NUMBER_FORMATTER = /*#__PURE__*/ new Intl.NumberFormat(undefined, {
  maximumSignificantDigits: 3,
});

const STANDARD_NUMBER_FORMATTER = /*#__PURE__*/ new Intl.NumberFormat(undefined, {
  maximumFractionDigits: 2,
});

export {
  SVG_NS,
  ChartType,
  ChartOrientation,
  YAxisPosition,
  CHART_ORIENTATIONS,
  Y_AXIS_POSITIONS,
  DEFAULT_COLORS,
  HEATMAP_COLORS,
  CARTESIAN_TYPES,
  AGGREGATION_TYPES,
  TYPES,
  MAJOR_GRID_DIVISIONS,
  MAX_INDIVIDUAL_LINE_POINTS,
  MAX_X_INSPECTOR_POINTS,
  HORIZONTAL_LABEL_EDGE_INSET,
  HORIZONTAL_LABEL_GAP,
  VALUE_LABEL_GAP,
  SERIES_SWATCH_DIAMETER,
  LEGEND_LABEL_OFFSET,
  LEGEND_ROW_HEIGHT,
  LEGEND_BASELINE_INSET,
  LEGEND_CONTENT_GAP,
  MULTILINE_LABEL_HEIGHT,
  POLAR_LABEL_EDGE_INSET,
  POLAR_LABEL_GAP,
  POLAR_LABEL_MIN_WIDTH,
  DEFAULT_PAD_ANGLE,
  DEFAULT_BAR_RADIUS,
  DEFAULT_SECTOR_CORNER_RADIUS,
  DEFAULT_PERCENTAGE_RADIUS,
  MIN_SECTOR_SWEEP,
  HEATMAP_MIN_CELL_WIDTH,
  HOUR,
  DAY,
  TIME_TICK_STEPS,
  COMPACT_NUMBER_FORMATTER,
  SMALL_NUMBER_FORMATTER,
  STANDARD_NUMBER_FORMATTER,
};

export {
  CHART_LINE,
  CHART_BAR,
  CHART_SCATTER,
  CHART_AXIS_MIXED,
  CHART_BUBBLE,
  CHART_PIE,
  CHART_DONUT,
  CHART_PERCENTAGE,
  CHART_RADAR,
  CHART_POLAR_AREA,
  CHART_HEATMAP,
  CHART_TIMESHEET,
};

export { ORIENTATION_HORIZONTAL, ORIENTATION_VERTICAL };

export { Y_AXIS_LEFT, Y_AXIS_RIGHT };
